Fixed rescue ConditionPathExists flag
While looking at some logs, I discovered that systemd was now erroring about
the ConditionPathExists parameter. It appears that belongs in unit instead.

As such, moving.

Error: systemd[1]: /usr/lib/systemd/system/ironic-python-agent.service:6: Unknown key name 'ConditionPathExists' in section 'Service', ignoring.

Change-Id: Ifc2b2cbde939d9d9b9fec4e9a5f548e5420650a2
Signed-off-by: Julia Kreger <juliaashleykreger@gmail.com>
(cherry picked from commit 9c877b2a9061c6fd5c1c64b2817d0918933d5dcc)